name: WindConsumer EC2 배포

on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Gradle로 프로젝트 빌드
        run: ./gradlew clean bootJar

      - name: SSH 프라이빗 키 저장
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: 빌드된 JAR 파일을 EC2로 복사
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no \
            build/libs/WindConsumer-*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/wind.jar

      - name: EC2에 SSH 접속해 서버 재시작
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              echo "=== WindConsumer 배포 시작 ==="
              
              # 1단계: 정중한 프로세스 종료 (SIGTERM)
              echo "기존 프로세스 정중한 종료 중..."
              pkill -f 'java -jar.*wind.jar' || true
              sleep 10
              
              # 2단계: 강제 프로세스 종료 (SIGKILL)
              echo "남은 프로세스 강제 종료 중..."
              pkill -9 -f 'java -jar.*wind.jar' || true
              
              # 3단계: 포트 기반 강제 종료 (8084 포트)
              echo "포트 8084 사용 프로세스 강제 종료 중..."
              sudo lsof -ti:8084 | xargs -r sudo kill -9 2>/dev/null || true
              
              # 4단계: 포트 해제 대기
              echo "포트 8084 해제 대기 중..."
              timeout=30
              while [ $timeout -gt 0 ] && lsof -Pi:8084 -sTCP:LISTEN -t >/dev/null 2>&1; do
                echo "포트 8084가 아직 사용 중입니다. 대기 중... ($timeout초 남음)"
                sleep 2
                timeout=$((timeout-2))
              done
              
              if lsof -Pi:8084 -sTCP:LISTEN -t >/dev/null 2>&1; then
                echo "⚠️  포트 8084 해제 실패. 강제로 진행합니다."
              else
                echo "✅ 포트 8084가 해제되었습니다."
              fi
              
              # 기존 로그 파일 삭제
              rm -f wind.log
              
              # 5단계: 새로운 애플리케이션 시작
              echo "새로운 WindConsumer 애플리케이션 시작 중..."
              nohup java -jar /home/${USER}/wind.jar > wind.log 2>&1 &
              
              # 6단계: 애플리케이션 시작 확인
              echo "애플리케이션 시작 확인 중..."
              sleep 15
              
              # 프로세스 확인
              if pgrep -f 'java -jar.*wind.jar' > /dev/null; then
                echo "✅ 프로세스가 실행 중입니다."
                
                # 포트 리스닝 확인
                sleep 5
                if lsof -Pi:8084 -sTCP:LISTEN -t >/dev/null 2>&1; then
                  echo "✅ 포트 8084에서 리스닝 중입니다."
                  echo "✅ WindConsumer 애플리케이션이 성공적으로 시작되었습니다!"
                else
                  echo "⚠️  프로세스는 실행 중이지만 포트 8084에서 리스닝하지 않습니다."
                  echo "로그를 확인하세요:"
                  tail -20 wind.log
                fi
              else
                echo "❌ WindConsumer 애플리케이션 시작 실패!"
                echo "로그를 확인하세요:"
                tail -20 wind.log
                exit 1
              fi
              
              echo "=== WindConsumer 배포 완료 ==="
          EOF